@baseUri=http://localhost:3000/api 

### generate wallpaper
POST {{baseUri}}/protected/gen-wallpaper
Content-Type: application/json

{
    "description": "happy new year 2024"
}

### get wallpapers
POST {{baseUri}}/get-wallpapers
Content-Type: application/json

{
    "page": 1
}

### checkout
POST {{baseUri}}/checkout
Content-Type: application/json

{
    "page": 1
}


### repswap params
POST {{baseUri}}/repswap
Content-Type: application/json

{
    "swap_image": "https://www.telegraph.co.uk/multimedia/archive/03249/archetypal-female-_3249633c.jpg",
    "target_image": "https://replicate.delivery/pbxt/JoBuz3wGiVFQ1TDEcsGZbYcNh0bHpvwOi32T1fmxhRujqcu7/9X2.png"
}
